name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: ["11.0.6", "13.0.2"]
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg JDK_VERSION=${{ matrix.jdk }} --tag chmodas/openjdk-docker-compose:${{ matrix.jdk }}
    - name: Publish the Docker image
      if: github.ref == 'master'
      run: |
        echo ${{ secrets.DOCKER_HUB }} | docker login --username ${{ secrets.DOCKER_UID }} --password-stdin
        docker push chmodas/openjdk-docker-compose:${{ matrix.jdk }}
        docker logout
